apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label.app }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  selector: # how the Deployment object will select Pods to manage
    matchLabels:
      app: {{ .Values.label.app }}-app
  template: # the template that will be used to create Pods
    metadata:
19
    metadata:
      labels: 
        app: {{ .Values.label.app }}-app
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: {{ .Values.label.app }}-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports: # information about the network connections a container uses
            - name: http
              containerPort: 80
              protocol: TCP
