apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
     app: {{ .Values.label.app }}-app
spec:
  ports:
  - name: http
    # port: for the service (used for other pods to communicate with the service)
    port: {{ .Values.service.port }}
    # targetPort: the port number of the container inside the pod that the service forwards 
    targetPort: {{ .Values.service.targetPort }}
    # nodePort: The gateway on the node to communicate with the pod (<nod_ip>:<nodePort>)
    # nodePort: 32123
  selector: # the pods it should route traffic to.
    app: {{ .Values.label.app }}-app
  type: {{ .Values.service.type }}
