apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyYXl0bzk5MSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfOVFIYmc3REpOWmVfaGY4bWNHRFZVdUo5TVJzIiwiYXV0aCI6ImNtRjVkRzg1T1RFNlpHTnJjbDl3WVhSZk9WRklZbWMzUkVwT1dtVmZhR1k0YldOSFJGWlZkVW81VFZKeiJ9fX0=
