apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: jenkins-server
  type: {{ .Values.service.type }}
  ports:
    - name: httpport
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: 30200
    - name: jnlpport
      port: 50000
      targetPort: 50000
