apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: {{ .Values.namespace }}
data:
  gitlab.rb: |
    # external_url 'http://gitlab.example.com'
    external_url 'http://192.168.49.2/' # minikube ip
    gitlab_rails['initial_root_password'] = '{{ .Values.gitlab_server.init_password }}'
