apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label.gitlab }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: # how the Deployment object will select Pods to manage
    matchLabels:
      app: {{ .Values.label.gitlab }}-app
  template: # the template that will be used to create Pods
    metadata:
      labels:
        app: {{ .Values.label.gitlab }}-app
    spec:
      containers:
        - name: {{ .Values.label.gitlab }}-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports: # information about the network connections a container uses
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: gitlab-config
                  key: gitlab.rb
          volumeMounts:
          - name: gitlab-data
            mountPath: /etc/gitlab
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-pv-claim
