kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-gitlab
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-volume
  labels:
    type: local-gitlab
spec:
  storageClassName: local-storage-gitlab
  claimRef:
    name: gitlab-pv-claim
    namespace: gitlab
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    #path: /mnt
    path: /home/gitlab/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pv-claim
  namespace: gitlab
spec:
  storageClassName: local-storage-gitlab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
